---
version: "3.8"

services:
#  uniexpress-backend:
#    build:
#      context: .
#      dockerfile: dockerfile
#    image: uniexpress-backend:latest
#    container_name: api-uniexpress-backend
#    ports:
#      - "8080:8080"
#    networks:
#      - uniexpress-nt

  database:
    image: mysql
    container_name: db-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    networks:
      - uniexpress-nt

networks:
  uniexpress-nt:
    name: uniexpress-nt
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/29
          gateway: 10.10.1.1